Fix bug where nested workflows would cause Inngest duplicate key error
```
Error: Duplicate function ID "mastra-workflow.{workflow_id}"; please change a function's name or provide an explicit ID to avoid conflicts.
    at /Users/knrz/Git/zenbase-ai/pixel/next/node_modules/.pnpm/inngest@3.39.2_express@5.1.0_hono@4.8.3_next@15.3.3_@babel+core@7.27.7_@opentelemetry+a_7ab62830c1c20a5df6d6a4bfc2eef686/node_modules/inngest/components/InngestCommHandler.js:134:27
    at Array.forEach (<anonymous>)
    at /Users/knrz/Git/zenbase-ai/pixel/next/node_modules/.pnpm/inngest@3.39.2_express@5.1.0_hono@4.8.3_next@15.3.3_@babel+core@7.27.7_@opentelemetry+a_7ab62830c1c20a5df6d6a4bfc2eef686/node_modules/inngest/components/InngestCommHandler.js:131:21
    at Array.reduce (<anonymous>)
    at new InngestCommHandler (/Users/knrz/Git/zenbase-ai/pixel/next/node_modules/.pnpm/inngest@3.39.2_express@5.1.0_hono@4.8.3_next@15.3.3_@babel+core@7.27.7_@opentelemetry+a_7ab62830c1c20a5df6d6a4bfc2eef686/node_modules/inngest/components/InngestCommHandler.js:123:32)
    at serve (/Users/knrz/Git/zenbase-ai/pixel/next/node_modules/.pnpm/inngest@3.39.2_express@5.1.0_hono@4.8.3_next@15.3.3_@babel+core@7.27.7_@opentelemetry+a_7ab62830c1c20a5df6d6a4bfc2eef686/node_modules/inngest/hono.js:49:21)
    at serve (file:///Users/knrz/Git/zenbase-ai/pixel/next/node_modules/.pnpm/@mastra+inngest@0.11.0_@mastra+core@0.10.8_openapi-types@12.1.3_react@19.1.0_zod@3.25.5_3fe46e4d0be4226ea166beba1c705198/node_modules/@mastra/inngest/dist/index.js:23:10)
    at Object.createHandler (file:///Users/knrz/Git/zenbase-ai/pixel/next/.mastra/output/index.mjs:744:15)
    at createHonoServer (file:///Users/knrz/Git/zenbase-ai/pixel/next/.mastra/output/index.mjs:12213:72)
    at async createNodeServer (file:///Users/knrz/Git/zenbase-ai/pixel/next/.mastra/output/index.mjs:15627:15)
```