ci: fix eslint error (#2515)
When running `cd packages/loggers && pnpm run lint` I was getting
`Error: Cannot find module
'@typescript-eslint/eslint-plugin/use-at-your-own-risk/eslint-recommended-raw'`.

With this change I see lint warnings:
```
/Users/tylerbarnes/code/mastra-ai/mastra/packages/loggers/src/file/index.test.ts
  1:1   warning  `@mastra/core/logger` import should occur after import of `path`                   import/order
  4:44  warning  'afterEach' is defined but never used. Allowed unused vars must match /^ignored/u  @typescript-eslint/no-unused-vars

/Users/tylerbarnes/code/mastra-ai/mastra/packages/loggers/src/file/index.ts
  3:1  warning  `fs` type import should occur before import of `@mastra/core/logger`  import/order
  4:1  warning  `fs` import should occur before import of `@mastra/core/logger`       import/order

/Users/tylerbarnes/code/mastra-ai/mastra/packages/loggers/src/upstash/index.test.ts
  107:11  warning  'errorObj' is assigned a value but never used. Allowed unused vars must match /^ignored/u  @typescript-eslint/no-unused-vars

/Users/tylerbarnes/code/mastra-ai/mastra/packages/loggers/src/upstash/index.ts
  156:18  warning  'e' is defined but never used  @typescript-eslint/no-unused-vars

✖ 6 problems (0 errors, 6 warnings)
  0 errors and 3 warnings potentially fixable with the `--fix` option.
```

Co-authored-by: Your Name <you@example.com>